// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// keyboardScan //
// ------------ //

#define keyboardScan_wrap_target 0
#define keyboardScan_wrap 9

static const uint16_t keyboardScan_program_instructions[] = {
            //     .wrap_target
    0xe00f, //  0: set    pins, 15                   
    0x4010, //  1: in     pins, 16                   
    0xe017, //  2: set    pins, 23                   
    0x4010, //  3: in     pins, 16                   
    0xe01b, //  4: set    pins, 27                   
    0x4010, //  5: in     pins, 16                   
    0xe01d, //  6: set    pins, 29                   
    0x4010, //  7: in     pins, 16                   
    0xe01e, //  8: set    pins, 30                   
    0x4010, //  9: in     pins, 16                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program keyboardScan_program = {
    .instructions = keyboardScan_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config keyboardScan_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + keyboardScan_wrap_target, offset + keyboardScan_wrap);
    return c;
}

// this is a raw helper function for use by the user which sets up the GPIO output, and configures the SM to output on a particular pin
void keyboardScan_program_init(PIO pio, uint sm, uint offset, uint pin) {
    for(int i =0;i<22;i++)
    {
        pio_gpio_init(pio, pin+i);
        if(i>5) gpio_pull_up(pin+i);
    }
   pio_sm_set_consecutive_pindirs(pio, sm, pin, 5, true);
   pio_sm_set_consecutive_pindirs(pio, sm, pin+6, 16, false);
   pio_sm_config c = keyboardScan_program_get_default_config(offset);
   sm_config_set_fifo_join(&c,PIO_FIFO_JOIN_RX);
   sm_config_set_set_pins(&c, pin,5);
   sm_config_set_in_pins(&c, pin+6);
   sm_config_set_in_shift(&c,false,true,16);
   pio_sm_init(pio, sm, offset, &c);
}

#endif

