#ifndef MAGIC63_CONFIG_H
#define MAGIC63_CONFIG_H

#ifndef MAGIC63_ENABLE_USB_CDC_DEBUG
#define MAGIC63_ENABLE_USB_CDC_DEBUG 0
#endif

#ifndef MAGIC63_ENABLE_UART_STDIO
#define MAGIC63_ENABLE_UART_STDIO 0
#endif

#ifndef MAGIC63_ENABLE_DEBUG_OUTPUT
#define MAGIC63_ENABLE_DEBUG_OUTPUT 0
#endif

#endif
